package edu.pitt.dbmi.ohdsiv5.db;
               # Replace Windows newlines with Unix newlines// Generated Aug 25, 2010 7:48:41 AM by Hibernate Tools 3.1.0.beta4
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlinesimport java.util.Calendar;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines/**
               # Replace Windows newlines with Unix newlines * ConceptRelationship generated by hbm2java
               # Replace Windows newlines with Unix newlines */
               # Replace Windows newlines with Unix newlines@Entity
               # Replace Windows newlines with Unix newlines@Table(name="CONCEPT_RELATIONSHIP", uniqueConstraints = {  })
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlinespublic class ConceptRelationship  {
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    // Fields    
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    private String relationshipId;
               # Replace Windows newlines with Unix newlines    private Integer conceptId1;
               # Replace Windows newlines with Unix newlines    private Integer conceptId2;
               # Replace Windows newlines with Unix newlines    private Calendar validStartDate;
               # Replace Windows newlines with Unix newlines    private Calendar validEndDate;
               # Replace Windows newlines with Unix newlines    private String invalidReason;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    // Constructors
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    /** default constructor */
               # Replace Windows newlines with Unix newlines    public ConceptRelationship() {
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    /** full constructor */
               # Replace Windows newlines with Unix newlines    public ConceptRelationship(String relationshipId, Integer conceptId1, Integer conceptId2) {
               # Replace Windows newlines with Unix newlines        this.relationshipId = relationshipId;
               # Replace Windows newlines with Unix newlines        this.conceptId1 = conceptId1;
               # Replace Windows newlines with Unix newlines        this.conceptId2 = conceptId2;	
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines   
               # Replace Windows newlines with Unix newlines    // Property accessors
               # Replace Windows newlines with Unix newlines    @Id
               # Replace Windows newlines with Unix newlines    @Column(name="RELATIONSHIP_ID", unique=true, nullable=false, insertable=true, updatable=true, length=20, scale=0)
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    public String getRelationshipId() {
               # Replace Windows newlines with Unix newlines        return this.relationshipId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    public void setRelationshipId(String relationshipId) {
               # Replace Windows newlines with Unix newlines        this.relationshipId = relationshipId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    @Column(name="CONCEPT_ID_1", unique=false, nullable=false, insertable=true, updatable=true, precision=22, scale=0)
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    public Integer getConceptId1() {
               # Replace Windows newlines with Unix newlines        return this.conceptId1;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    public void setConceptId1(Integer conceptId1) {
               # Replace Windows newlines with Unix newlines        this.conceptId1 = conceptId1;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    @Column(name="CONCEPT_ID_2", unique=false, nullable=false, insertable=true, updatable=true, precision=22, scale=0)
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    public Integer getConceptId2() {
               # Replace Windows newlines with Unix newlines        return this.conceptId2;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    public void setConceptId2(Integer conceptId2) {
               # Replace Windows newlines with Unix newlines        this.conceptId2 = conceptId2;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    @Column(name="VALID_START_DATE", unique=true, nullable=false, insertable=true, updatable=true, length=7)
               # Replace Windows newlines with Unix newlines    public Calendar getValidStartDate() {
               # Replace Windows newlines with Unix newlines	return validStartDate;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setValidStartDate(Calendar validStartDate) {
               # Replace Windows newlines with Unix newlines	this.validStartDate = validStartDate;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    @Column(name="VALID_END_DATE", unique=true, nullable=false, insertable=true, updatable=true, length=7)
               # Replace Windows newlines with Unix newlines    public Calendar getValidEndDate() {
               # Replace Windows newlines with Unix newlines	return validEndDate;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setValidEndDate(Calendar validEndDate) {
               # Replace Windows newlines with Unix newlines	this.validEndDate = validEndDate;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    @Column(name="INVALID_REASON", unique=true, nullable=true, insertable=true, updatable=true, length=1, scale=0)
               # Replace Windows newlines with Unix newlines    public String getInvalidReason() {
               # Replace Windows newlines with Unix newlines	return invalidReason;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setInvalidReason(String invalidReason) {
               # Replace Windows newlines with Unix newlines	this.invalidReason = invalidReason;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines}
               # Replace Windows newlines with Unix newlines