package edu.pitt.dbmi.ohdsiv5.db;
               # Replace Windows newlines with Unix newlines// Generated Aug 25, 2010 7:48:41 AM by Hibernate Tools 3.1.0.beta4
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlinesimport java.sql.Timestamp;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines/**
               # Replace Windows newlines with Unix newlines * ConceptRelationship generated by hbm2java
               # Replace Windows newlines with Unix newlines */
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlinespublic class ConceptRelationship  {
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    // Fields    
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    private String relationshipId;
               # Replace Windows newlines with Unix newlines    private Integer conceptId1;
               # Replace Windows newlines with Unix newlines    private Integer conceptId2;
               # Replace Windows newlines with Unix newlines    private Timestamp validStartDate;
               # Replace Windows newlines with Unix newlines    private Timestamp validEndDate;
               # Replace Windows newlines with Unix newlines    private String invalidReason;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    // Constructors
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    /** default constructor */
               # Replace Windows newlines with Unix newlines    public ConceptRelationship() {
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    /** full constructor */
               # Replace Windows newlines with Unix newlines    public ConceptRelationship(String relationshipId, Integer conceptId1, Integer conceptId2) {
               # Replace Windows newlines with Unix newlines        this.relationshipId = relationshipId;
               # Replace Windows newlines with Unix newlines        this.conceptId1 = conceptId1;
               # Replace Windows newlines with Unix newlines        this.conceptId2 = conceptId2;	
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines   
               # Replace Windows newlines with Unix newlines    // Property accessors
               # Replace Windows newlines with Unix newlines        
               # Replace Windows newlines with Unix newlines    public String getRelationshipId() {
               # Replace Windows newlines with Unix newlines        return this.relationshipId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    public void setRelationshipId(String relationshipId) {
               # Replace Windows newlines with Unix newlines        this.relationshipId = relationshipId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    public Integer getConceptId1() {
               # Replace Windows newlines with Unix newlines        return this.conceptId1;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    public void setConceptId1(Integer conceptId1) {
               # Replace Windows newlines with Unix newlines        this.conceptId1 = conceptId1;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    public Integer getConceptId2() {
               # Replace Windows newlines with Unix newlines        return this.conceptId2;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    public void setConceptId2(Integer conceptId2) {
               # Replace Windows newlines with Unix newlines        this.conceptId2 = conceptId2;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines        public Timestamp getValidStartDate() {
               # Replace Windows newlines with Unix newlines	return validStartDate;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setValidStartDate(Timestamp validStartDate) {
               # Replace Windows newlines with Unix newlines	this.validStartDate = validStartDate;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines        public Timestamp getValidEndDate() {
               # Replace Windows newlines with Unix newlines	return validEndDate;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setValidEndDate(Timestamp validEndDate) {
               # Replace Windows newlines with Unix newlines	this.validEndDate = validEndDate;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines        public String getInvalidReason() {
               # Replace Windows newlines with Unix newlines	return invalidReason;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setInvalidReason(String invalidReason) {
               # Replace Windows newlines with Unix newlines	this.invalidReason = invalidReason;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines}
               # Replace Windows newlines with Unix newlines