package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:38:53 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * ConditionOccurrenceRef generated by hbm2java
 */
@Entity
@Table(name="CONDITION_OCCURRENCE_REF")

public class ConditionOccurrenceRef  {


    // Fields    

     private Long id;


    // Constructors

    /** default constructor */
    public ConditionOccurrenceRef() {
    }

    
    /** full constructor */
    public ConditionOccurrenceRef(Long id) {
        this.id = id;
    }
    

   
    // Property accessors
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="conditionOccurrenceType", column=@Column(name="CONDITION_OCCURRENCE_TYPE", unique=false, nullable=false, insertable=true, updatable=true, length=3) ), 
        @AttributeOverride(name="conditionOccurrenceTypeDesc", column=@Column(name="CONDITION_OCCURRENCE_TYPE_DESC", unique=false, nullable=true, insertable=true, updatable=true, length=120) ), 
        @AttributeOverride(name="persistenceWindow", column=@Column(name="PERSISTENCE_WINDOW", unique=false, nullable=true, insertable=true, updatable=true, precision=22, scale=0) ), 
        @AttributeOverride(name="conditionOccurrencePosition", column=@Column(name="CONDITION_OCCURRENCE_POSITION", unique=false, nullable=true, insertable=true, updatable=true, length=20) ) } )

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   








}
