package edu.pitt.dbmi.ohdsiv5.db;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlinesimport java.util.Calendar;
               # Replace Windows newlines with Unix newlinesimport java.sql.Timestamp;
               # Replace Windows newlines with Unix newlinesimport javax.persistence.Column;
               # Replace Windows newlines with Unix newlinesimport javax.persistence.Entity;
               # Replace Windows newlines with Unix newlinesimport javax.persistence.GeneratedValue;
               # Replace Windows newlines with Unix newlinesimport javax.persistence.GenerationType;
               # Replace Windows newlines with Unix newlinesimport javax.persistence.Id;
               # Replace Windows newlines with Unix newlinesimport javax.persistence.SequenceGenerator;
               # Replace Windows newlines with Unix newlinesimport javax.persistence.Table;
               # Replace Windows newlines with Unix newlinesimport javax.persistence.Transient;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlinesimport edu.pitt.dbmi.ohdsiv5.db.DrugStrength;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines/**
               # Replace Windows newlines with Unix newlines * DrugExposure generated by hbm2java
               # Replace Windows newlines with Unix newlines */
               # Replace Windows newlines with Unix newlines@Entity
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlinespublic class ExtendedDrugExposure extends DrugExposure implements java.io.Serializable {
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    // Constructors
               # Replace Windows newlines with Unix newlines    /** default constructor */
               # Replace Windows newlines with Unix newlines    public ExtendedDrugExposure() {
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    /** full constructor */
               # Replace Windows newlines with Unix newlines    public ExtendedDrugExposure (Long drugExposureId,
               # Replace Windows newlines with Unix newlines            Calendar drugExposureStartDateCal,
               # Replace Windows newlines with Unix newlines            Calendar drugExposureEndDateCal,
               # Replace Windows newlines with Unix newlines            Timestamp drugExposureStartDate,
               # Replace Windows newlines with Unix newlines            Timestamp drugExposureEndDate,
               # Replace Windows newlines with Unix newlines            Long personId,
               # Replace Windows newlines with Unix newlines            Integer drugConceptId,
               # Replace Windows newlines with Unix newlines            Integer drugTypeConceptId,
               # Replace Windows newlines with Unix newlines            String stopReason,
               # Replace Windows newlines with Unix newlines            Short refills,
               # Replace Windows newlines with Unix newlines            Integer drugQuantity,
               # Replace Windows newlines with Unix newlines            Short daysSupply,
               # Replace Windows newlines with Unix newlines            String sig,
               # Replace Windows newlines with Unix newlines            Integer sigExpected,
               # Replace Windows newlines with Unix newlines            Integer sigMin,
               # Replace Windows newlines with Unix newlines            Integer sigMax,  
               # Replace Windows newlines with Unix newlines            Integer routeConceptId,
               # Replace Windows newlines with Unix newlines            String lotNumber,
               # Replace Windows newlines with Unix newlines            Integer providerId,
               # Replace Windows newlines with Unix newlines            Long visitOccurrenceId,
               # Replace Windows newlines with Unix newlines            String drugSourceValue,
               # Replace Windows newlines with Unix newlines            Integer drugSourceConceptId,
               # Replace Windows newlines with Unix newlines            String routeSourceValue,
               # Replace Windows newlines with Unix newlines            String doseUnitSourceValue,
               # Replace Windows newlines with Unix newlines            Integer ingredientConceptId,
               # Replace Windows newlines with Unix newlines            Double amountValue,
               # Replace Windows newlines with Unix newlines            Integer amountUnitConceptId,
               # Replace Windows newlines with Unix newlines            Double numeratorValue,
               # Replace Windows newlines with Unix newlines            Integer numeratorUnitConceptId,
               # Replace Windows newlines with Unix newlines            Double denominatorValue,
               # Replace Windows newlines with Unix newlines            Integer denominatorUnitConceptId,
               # Replace Windows newlines with Unix newlines            Double dailyDosage,
               # Replace Windows newlines with Unix newlines            Integer indicationConceptId
               # Replace Windows newlines with Unix newlines            ) {
               # Replace Windows newlines with Unix newlines    this.drugExposureId = drugExposureId;
               # Replace Windows newlines with Unix newlines        this.drugExposureStartDateCal = drugExposureStartDateCal;
               # Replace Windows newlines with Unix newlines        this.drugExposureEndDateCal = drugExposureEndDateCal;
               # Replace Windows newlines with Unix newlines    this.drugExposureStartDate = drugExposureStartDate;
               # Replace Windows newlines with Unix newlines        this.drugExposureEndDate = drugExposureEndDate;
               # Replace Windows newlines with Unix newlines        this.personId = personId;
               # Replace Windows newlines with Unix newlines        this.drugConceptId = drugConceptId;
               # Replace Windows newlines with Unix newlines        this.drugTypeConceptId = drugTypeConceptId;
               # Replace Windows newlines with Unix newlines        this.stopReason = stopReason;
               # Replace Windows newlines with Unix newlines        this.refills = refills;
               # Replace Windows newlines with Unix newlines        this.drugQuantity = drugQuantity;
               # Replace Windows newlines with Unix newlines        this.daysSupply = daysSupply;
               # Replace Windows newlines with Unix newlines    this.sig = sig;
               # Replace Windows newlines with Unix newlines    this.sigExpected = sigExpected;
               # Replace Windows newlines with Unix newlines    this.sigMin = sigMin;
               # Replace Windows newlines with Unix newlines    this.sigMax = sigMax;
               # Replace Windows newlines with Unix newlines    this.routeConceptId = routeConceptId;
               # Replace Windows newlines with Unix newlines    this.lotNumber = lotNumber;
               # Replace Windows newlines with Unix newlines    this.providerId = providerId;
               # Replace Windows newlines with Unix newlines    this.visitOccurrenceId = visitOccurrenceId;
               # Replace Windows newlines with Unix newlines    this.drugSourceValue = drugSourceValue;
               # Replace Windows newlines with Unix newlines    this.drugSourceConceptId = drugSourceConceptId;
               # Replace Windows newlines with Unix newlines    this.routeSourceValue = routeSourceValue;
               # Replace Windows newlines with Unix newlines    this.doseUnitSourceValue = doseUnitSourceValue;
               # Replace Windows newlines with Unix newlines    this.ingredientConceptId = ingredientConceptId;
               # Replace Windows newlines with Unix newlines    this.amountValue = amountValue;
               # Replace Windows newlines with Unix newlines    this.amountUnitConceptId = amountUnitConceptId;
               # Replace Windows newlines with Unix newlines    this.numeratorValue = numeratorValue;
               # Replace Windows newlines with Unix newlines    this.numeratorUnitConceptId = numeratorUnitConceptId;
               # Replace Windows newlines with Unix newlines    this.denominatorValue = denominatorValue;
               # Replace Windows newlines with Unix newlines    this.denominatorUnitConceptId = denominatorUnitConceptId;
               # Replace Windows newlines with Unix newlines    this.dailyDosage = dailyDosage;
               # Replace Windows newlines with Unix newlines    this.indicationConceptId = indicationConceptId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    Calendar drugExposureStartDateCal;
               # Replace Windows newlines with Unix newlines    public Calendar getDrugExposureStartDateCal() {
               # Replace Windows newlines with Unix newlines        return this.drugExposureStartDateCal;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setDrugExposureStartDateCal(Calendar drugExposureStartDateCal) {
               # Replace Windows newlines with Unix newlines        this.drugExposureStartDateCal = drugExposureStartDateCal;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    Calendar drugExposureEndDateCal;
               # Replace Windows newlines with Unix newlines    public Calendar getDrugExposureEndDateCal() {
               # Replace Windows newlines with Unix newlines        return this.drugExposureEndDateCal;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setDrugExposureEndDateCal(Calendar drugExposureEndDateCal) {
               # Replace Windows newlines with Unix newlines        this.drugExposureEndDateCal = drugExposureEndDateCal;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    @Transient
               # Replace Windows newlines with Unix newlines    Integer sigExpected;
               # Replace Windows newlines with Unix newlines    public Integer getSigExpected() {
               # Replace Windows newlines with Unix newlines        return this.sigExpected;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setSigExpected(Integer sigExpected) {
               # Replace Windows newlines with Unix newlines        this.sigExpected = sigExpected;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    @Transient
               # Replace Windows newlines with Unix newlines    Integer sigMin;
               # Replace Windows newlines with Unix newlines    public Integer getSigMin() {
               # Replace Windows newlines with Unix newlines        return this.sigMin;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setSigMin(Integer sigMin) {
               # Replace Windows newlines with Unix newlines        this.sigMin = sigMin;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    @Transient
               # Replace Windows newlines with Unix newlines    Integer sigMax;
               # Replace Windows newlines with Unix newlines    public Integer getSigMax() {
               # Replace Windows newlines with Unix newlines        return this.sigMax;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setSigMax(Integer sigMax) {
               # Replace Windows newlines with Unix newlines        this.sigMax = sigMax;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    @Transient
               # Replace Windows newlines with Unix newlines    Integer ingredientConceptId;
               # Replace Windows newlines with Unix newlines    public Integer getIngredientConceptId() {
               # Replace Windows newlines with Unix newlines    return this.ingredientConceptId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setIngredientConceptId(Integer ingredientConceptId) {
               # Replace Windows newlines with Unix newlines    this.ingredientConceptId = ingredientConceptId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    @Transient
               # Replace Windows newlines with Unix newlines    Double amountValue;
               # Replace Windows newlines with Unix newlines    public Double getAmountValue() {
               # Replace Windows newlines with Unix newlines        return this.amountValue;
               # Replace Windows newlines with Unix newlines    }    
               # Replace Windows newlines with Unix newlines    public void setAmountValue(Double amountValue) {
               # Replace Windows newlines with Unix newlines        this.amountValue = amountValue;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines       
               # Replace Windows newlines with Unix newlines    @Transient
               # Replace Windows newlines with Unix newlines    Integer amountUnitConceptId;
               # Replace Windows newlines with Unix newlines    public Integer getAmountUnitConceptId() {
               # Replace Windows newlines with Unix newlines    return this.amountUnitConceptId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setAmountUnitConceptId(Integer amountUnitConceptId) {
               # Replace Windows newlines with Unix newlines    this.amountUnitConceptId = amountUnitConceptId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    @Transient
               # Replace Windows newlines with Unix newlines    Double numeratorValue;
               # Replace Windows newlines with Unix newlines    public Double getNumeratorValue() {
               # Replace Windows newlines with Unix newlines    return this.numeratorValue;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setNumeratorValue(Double numeratorValue) {
               # Replace Windows newlines with Unix newlines    this.numeratorValue = numeratorValue;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    @Transient
               # Replace Windows newlines with Unix newlines    Integer numeratorUnitConceptId;
               # Replace Windows newlines with Unix newlines    public Integer getNumeratorUnitConceptId() {
               # Replace Windows newlines with Unix newlines    return this.numeratorUnitConceptId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setNumeratorUnitConceptId(Integer numeratorUnitConceptId) {
               # Replace Windows newlines with Unix newlines    this.numeratorUnitConceptId = numeratorUnitConceptId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    @Transient
               # Replace Windows newlines with Unix newlines    Double denominatorValue;
               # Replace Windows newlines with Unix newlines    public Double getDenominatorValue() {
               # Replace Windows newlines with Unix newlines    return this.denominatorValue;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setDenominatorValue(Double denominatorValue) {
               # Replace Windows newlines with Unix newlines    this.denominatorValue = denominatorValue;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    
               # Replace Windows newlines with Unix newlines    @Transient
               # Replace Windows newlines with Unix newlines    Integer denominatorUnitConceptId;
               # Replace Windows newlines with Unix newlines    public Integer getDenominatorUnitConceptId() {
               # Replace Windows newlines with Unix newlines    return this.denominatorUnitConceptId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setDenominatorUnitConceptId(Integer denominatorUnitConceptId) {
               # Replace Windows newlines with Unix newlines    this.denominatorUnitConceptId = denominatorUnitConceptId;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines    @Transient
               # Replace Windows newlines with Unix newlines    Double dailyDosage;
               # Replace Windows newlines with Unix newlines    public Double getDailyDosage() {
               # Replace Windows newlines with Unix newlines        return this.dailyDosage;
               # Replace Windows newlines with Unix newlines    }    
               # Replace Windows newlines with Unix newlines    public void setNullDailyDosage(Double amountValue) {
               # Replace Windows newlines with Unix newlines    this.dailyDosage = amountValue;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setRegDailyDosage(Integer drugQuantity, Short daysSupply, Double amountValue) {
               # Replace Windows newlines with Unix newlines    dailyDosage = ((drugQuantity * amountValue) / daysSupply);
               # Replace Windows newlines with Unix newlines    this.dailyDosage = dailyDosage;               
               # Replace Windows newlines with Unix newlines    }  
               # Replace Windows newlines with Unix newlines    public void setComplexDailyDosage(Integer drugQuantity, Short daysSupply, Double numeratorValue){
               # Replace Windows newlines with Unix newlines    dailyDosage = ((drugQuantity * numeratorValue) / daysSupply);
               # Replace Windows newlines with Unix newlines    this.dailyDosage = dailyDosage;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines    public void setSigDailyDosage(Double amountValue, Double sigExpected) {
               # Replace Windows newlines with Unix newlines        dailyDosage = amountValue * sigExpected;
               # Replace Windows newlines with Unix newlines        this.dailyDosage = dailyDosage;
               # Replace Windows newlines with Unix newlines    }
               # Replace Windows newlines with Unix newlines}
               # Replace Windows newlines with Unix newlines 
               # Replace Windows newlines with Unix newlines