package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:43:41 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * DrugExposureRef generated by hbm2java
 */
@Entity
@Table(name="DRUG_EXPOSURE_REF")

public class DrugExposureRef  {


    // Fields    

     private DrugExposureRefId id;


    // Constructors

    /** default constructor */
    public DrugExposureRef() {
    }

    
    /** full constructor */
    public DrugExposureRef(DrugExposureRefId id) {
        this.id = id;
    }
    

   
    // Property accessors
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="drugExposureType", column=@Column(name="DRUG_EXPOSURE_TYPE", unique=false, nullable=false, insertable=true, updatable=true, length=3) ), 
        @AttributeOverride(name="drugExposureTypeDesc", column=@Column(name="DRUG_EXPOSURE_TYPE_DESC", unique=false, nullable=true, insertable=true, updatable=true, length=120) ), 
        @AttributeOverride(name="persistenceWindow", column=@Column(name="PERSISTENCE_WINDOW", unique=false, nullable=true, insertable=true, updatable=true, precision=22, scale=0) ) } )

    public DrugExposureRefId getId() {
        return this.id;
    }
    
    public void setId(DrugExposureRefId id) {
        this.id = id;
    }
   








}
