package edu.pitt.dbmi.ohdsiv5.db;

import java.util.Calendar;
import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import edu.pitt.dbmi.ohdsiv5.db.DrugStrength;

/**
 * DrugExposure generated by hbm2java
 */
@Entity

public class ExtendedDrugExposure extends DrugExposure implements java.io.Serializable {

    // Constructors
    /** default constructor */
    public ExtendedDrugExposure() {
    }
    /** full constructor */
    public ExtendedDrugExposure (Long drugExposureId,
            Calendar drugExposureStartDateCal,
            Calendar drugExposureEndDateCal,
            Timestamp drugExposureStartDate,
            Timestamp drugExposureEndDate,
            Long personId,
            Integer drugConceptId,
            Integer drugTypeConceptId,
            String stopReason,
            Short refills,
            Integer drugQuantity,
            Short daysSupply,
            String sig,
            Integer sigExpected,
            Integer sigMin,
            Integer sigMax,  
            Integer routeConceptId,
            String lotNumber,
            Integer providerId,
            Long visitOccurrenceId,
            String drugSourceValue,
            Integer drugSourceConceptId,
            String routeSourceValue,
            String doseUnitSourceValue,
            Integer ingredientConceptId,
            Double amountValue,
            Integer amountUnitConceptId,
            Double numeratorValue,
            Integer numeratorUnitConceptId,
            Double denominatorValue,
            Integer denominatorUnitConceptId,
            Double dailyDosage,
            Integer indicationConceptId
            ) {
        this.drugExposureId = drugExposureId;
        this.drugExposureStartDateCal = drugExposureStartDateCal;
        this.drugExposureEndDateCal = drugExposureEndDateCal;
        this.drugExposureStartDate = drugExposureStartDate;
        this.drugExposureEndDate = drugExposureEndDate;
        this.personId = personId;
        this.drugConceptId = drugConceptId;
        this.drugTypeConceptId = drugTypeConceptId;
        this.stopReason = stopReason;
        this.refills = refills;
        this.drugQuantity = drugQuantity;
        this.daysSupply = daysSupply;
        this.sig = sig;
        this.sigExpected = sigExpected;
        this.sigMin = sigMin;
        this.sigMax = sigMax;
        this.routeConceptId = routeConceptId;
        this.lotNumber = lotNumber;
        this.providerId = providerId;
        this.visitOccurrenceId = visitOccurrenceId;
        this.drugSourceValue = drugSourceValue;
        this.drugSourceConceptId = drugSourceConceptId;
        this.routeSourceValue = routeSourceValue;
        this.doseUnitSourceValue = doseUnitSourceValue;
        this.ingredientConceptId = ingredientConceptId;
        this.amountValue = amountValue;
        this.amountUnitConceptId = amountUnitConceptId;
        this.numeratorValue = numeratorValue;
        this.numeratorUnitConceptId = numeratorUnitConceptId;
        this.denominatorValue = denominatorValue;
        this.denominatorUnitConceptId = denominatorUnitConceptId;
        this.dailyDosage = dailyDosage;
        this.indicationConceptId = indicationConceptId;
    }

    Calendar drugExposureStartDateCal;
    public Calendar getDrugExposureStartDateCal() {
        return this.drugExposureStartDateCal;
    }
    public void setDrugExposureStartDateCal(Calendar drugExposureStartDateCal) {
        this.drugExposureStartDateCal = drugExposureStartDateCal;
    }
    
    Calendar drugExposureEndDateCal;
    public Calendar getDrugExposureEndDateCal() {
        return this.drugExposureEndDateCal;
    }
    public void setDrugExposureEndDateCal(Calendar drugExposureEndDateCal) {
        this.drugExposureEndDateCal = drugExposureEndDateCal;
    }
    

    @Transient
    Integer sigExpected;
    public Integer getSigExpected() {
        return this.sigExpected;
    }
    public void setSigExpected(Integer sigExpected) {
        this.sigExpected = sigExpected;
    }

    @Transient
    Integer sigMin;
    public Integer getSigMin() {
        return this.sigMin;
    }
    public void setSigMin(Integer sigMin) {
        this.sigMin = sigMin;
    }

    @Transient
    Integer sigMax;
    public Integer getSigMax() {
        return this.sigMax;
    }
    public void setSigMax(Integer sigMax) {
        this.sigMax = sigMax;
    }


    @Transient
    Integer ingredientConceptId;
    public Integer getIngredientConceptId() {
    return this.ingredientConceptId;
    }
    public void setIngredientConceptId(Integer ingredientConceptId) {
    this.ingredientConceptId = ingredientConceptId;
    }
    
    @Transient
    Double amountValue;
    public Double getAmountValue() {
        return this.amountValue;
    }    
    public void setAmountValue(Double amountValue) {
        this.amountValue = amountValue;
    }
       
    @Transient
    Integer amountUnitConceptId;
    public Integer getAmountUnitConceptId() {
    return this.amountUnitConceptId;
    }
    public void setAmountUnitConceptId(Integer amountUnitConceptId) {
    this.amountUnitConceptId = amountUnitConceptId;
    }

    @Transient
    Double numeratorValue;
    public Double getNumeratorValue() {
    return this.numeratorValue;
    }
    public void setNumeratorValue(Double numeratorValue) {
    this.numeratorValue = numeratorValue;
    }

    @Transient
    Integer numeratorUnitConceptId;
    public Integer getNumeratorUnitConceptId() {
    return this.numeratorUnitConceptId;
    }
    public void setNumeratorUnitConceptId(Integer numeratorUnitConceptId) {
    this.numeratorUnitConceptId = numeratorUnitConceptId;
    }

    @Transient
    Double denominatorValue;
    public Double getDenominatorValue() {
    return this.denominatorValue;
    }
    public void setDenominatorValue(Double denominatorValue) {
    this.denominatorValue = denominatorValue;
    }
    
    @Transient
    Integer denominatorUnitConceptId;
    public Integer getDenominatorUnitConceptId() {
    return this.denominatorUnitConceptId;
    }
    public void setDenominatorUnitConceptId(Integer denominatorUnitConceptId) {
    this.denominatorUnitConceptId = denominatorUnitConceptId;
    }

    @Transient
    Double dailyDosage;
    public Double getDailyDosage() {
        return this.dailyDosage;
    }    
    public void setNullDailyDosage(Double amountValue) {
    this.dailyDosage = amountValue;
    }
    public void setRegDailyDosage(Integer drugQuantity, Short daysSupply, Double amountValue) {
    dailyDosage = ((drugQuantity * amountValue) / daysSupply);
    this.dailyDosage = dailyDosage;               
    }  
    public void setComplexDailyDosage(Integer drugQuantity, Short daysSupply, Double numeratorValue){
    dailyDosage = ((drugQuantity * numeratorValue) / daysSupply);
    this.dailyDosage = dailyDosage;
    }
    public void setSigDailyDosage(Double amountValue, Double sigExpected) {
        dailyDosage = amountValue * sigExpected;
        this.dailyDosage = dailyDosage;
    }
}
 
