package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:43:41 PM by Hibernate Tools 3.1.0.beta4



/**
 * HoiOccurrence generated by hbm2java
 */
@Entity
@Table(name="HOI_OCCURRENCE")

public class HoiOccurrence  {


    // Fields    

     private Long id;


    // Constructors

    /** default constructor */
    public HoiOccurrence() {
    }

    
    /** full constructor */
    public HoiOccurrence(Long id) {
        this.id = id;
    }
    

   
    // Property accessors
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="Long", column=@Column(name="HOI_OCCURRENCE_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=15, scale=0) ), 
        @AttributeOverride(name="hoiConceptId", column=@Column(name="HOI_CONCEPT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=15, scale=0) ), 
        @AttributeOverride(name="personId", column=@Column(name="PERSON_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=15, scale=0) ), 
        @AttributeOverride(name="hoiIndexDate", column=@Column(name="HOI_INDEX_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=7) ) } )

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   








}
