package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:38:53 PM by Hibernate Tools 3.1.0.beta4



/**
 * HoiRef generated by hbm2java
 */
@Entity
@Table(name="HOI_REF")

public class HoiRef  {


    // Fields    

     private Long id;


    // Constructors

    /** default constructor */
    public HoiRef() {
    }

    
    /** full constructor */
    public HoiRef(Long id) {
        this.id = id;
    }
    

   
    // Property accessors
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="hoiConceptId", column=@Column(name="HOI_CONCEPT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=15, scale=0) ), 
        @AttributeOverride(name="hoiConditionId", column=@Column(name="HOI_CONDITION_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=15, scale=0) ), 
        @AttributeOverride(name="hoiConditionName", column=@Column(name="HOI_CONDITION_NAME", unique=false, nullable=false, insertable=true, updatable=true) ), 
        @AttributeOverride(name="hoiDefinitionId", column=@Column(name="HOI_DEFINITION_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=15, scale=0) ), 
        @AttributeOverride(name="hoiDescription", column=@Column(name="HOI_DESCRIPTION", unique=false, nullable=false, insertable=true, updatable=true, length=2000) ) } )

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   








}
