package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:44:59 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * OmopDrugEra generated by hbm2java
 */
@Entity
@Table(name="OMOP_DRUG_ERA")

public class OmopDrugEra  {


    // Fields    

     private Long id;


    // Constructors

    /** default constructor */
    public OmopDrugEra() {
    }

    
    /** full constructor */
    public OmopDrugEra(Long id) {
        this.id = id;
    }
    

   
    // Property accessors
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="drugEraId", column=@Column(name="DRUG_ERA_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=15, scale=0) ), 
        @AttributeOverride(name="drugEraStartDate", column=@Column(name="DRUG_ERA_START_DATE", unique=false, nullable=true, insertable=true, updatable=true, length=7) ), 
        @AttributeOverride(name="drugEraEndDate", column=@Column(name="DRUG_ERA_END_DATE", unique=false, nullable=true, insertable=true, updatable=true, length=7) ), 
        @AttributeOverride(name="personId", column=@Column(name="PERSON_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=15, scale=0) ), 
        @AttributeOverride(name="drugExposureType", column=@Column(name="DRUG_EXPOSURE_TYPE", unique=false, nullable=false, insertable=true, updatable=true, length=3) ), 
        @AttributeOverride(name="drugConceptId", column=@Column(name="DRUG_CONCEPT_ID", unique=false, nullable=true, insertable=true, updatable=true, precision=15, scale=0) ), 
        @AttributeOverride(name="drugExposureCount", column=@Column(name="DRUG_EXPOSURE_COUNT", unique=false, nullable=true, insertable=true, updatable=true, precision=5, scale=0) ) } )

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   








}
