package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:47:01 PM by Hibernate Tools 3.1.0.beta4



/**
 * ProcOccurrenceRef generated by hbm2java
 */
@Entity
@Table(name="PROC_OCCURRENCE_REF")

public class ProcOccurrenceRef  {


    // Fields    

     private Long id;


    // Constructors

    /** default constructor */
    public ProcOccurrenceRef() {
    }

    
    /** full constructor */
    public ProcOccurrenceRef(Long id) {
        this.id = id;
    }
    

   
    // Property accessors
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="procedureOccurrenceType", column=@Column(name="PROCEDURE_OCCURRENCE_TYPE", unique=false, nullable=false, insertable=true, updatable=true, length=3) ), 
        @AttributeOverride(name="procedureOccurrenceTypDesc", column=@Column(name="PROCEDURE_OCCURRENCE_TYP_DESC", unique=false, nullable=true, insertable=true, updatable=true, length=256) ), 
        @AttributeOverride(name="procedureOccurrencePosition", column=@Column(name="PROCEDURE_OCCURRENCE_POSITION", unique=false, nullable=true, insertable=true, updatable=true, length=20) ) } )

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   








}
