package edu.pitt.dbmi.ohdsiv5.db;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlinesimport java.util.List;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines/**
               # Replace Windows newlines with Unix newlines * SourceToConceptMap generated by hbm2java
               # Replace Windows newlines with Unix newlines */
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public class SourceToConceptMap  {
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	// Fields    
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	/**
               # Replace Windows newlines with Unix newlines	 * 
               # Replace Windows newlines with Unix newlines	 */
               # Replace Windows newlines with Unix newlines	private static final long serialVersionUID = 1L;
               # Replace Windows newlines with Unix newlines	private Integer sourceToConceptMapId;
               # Replace Windows newlines with Unix newlines	private String sourceCode;
               # Replace Windows newlines with Unix newlines	private String sourceCodeDescription;
               # Replace Windows newlines with Unix newlines	private String mappingType;
               # Replace Windows newlines with Unix newlines	private Integer targetConceptId;
               # Replace Windows newlines with Unix newlines	private Integer targetVocabularyId;
               # Replace Windows newlines with Unix newlines	private Integer sourceVocabularyId;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	// Constructors
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	/** default constructor */
               # Replace Windows newlines with Unix newlines	public SourceToConceptMap() {
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	/** minimal constructor */
               # Replace Windows newlines with Unix newlines	public SourceToConceptMap(String sourceCode, String mappingType, Integer targetConceptId, Integer targetVocabularyId, Integer sourceVocabularyId) {
               # Replace Windows newlines with Unix newlines		this.sourceCode = sourceCode;
               # Replace Windows newlines with Unix newlines		this.mappingType = mappingType;
               # Replace Windows newlines with Unix newlines		this.targetConceptId = targetConceptId;
               # Replace Windows newlines with Unix newlines		this.targetVocabularyId = targetVocabularyId;
               # Replace Windows newlines with Unix newlines		this.sourceVocabularyId = sourceVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	/** full constructor */
               # Replace Windows newlines with Unix newlines	public SourceToConceptMap(String sourceCode, String sourceCodeDescription, String mappingType, Integer targetConceptId, Integer targetVocabularyId, Integer sourceVocabularyId) {
               # Replace Windows newlines with Unix newlines		this.sourceCode = sourceCode;
               # Replace Windows newlines with Unix newlines		this.sourceCodeDescription = sourceCodeDescription;
               # Replace Windows newlines with Unix newlines		this.mappingType = mappingType;
               # Replace Windows newlines with Unix newlines		this.targetConceptId = targetConceptId;
               # Replace Windows newlines with Unix newlines		this.targetVocabularyId = targetVocabularyId;
               # Replace Windows newlines with Unix newlines		this.sourceVocabularyId = sourceVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	// Property accessors
               # Replace Windows newlines with Unix newlines			public String getSourceCode() {
               # Replace Windows newlines with Unix newlines		return this.sourceCode;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setSourceCode(String sourceCode) {
               # Replace Windows newlines with Unix newlines		this.sourceCode = sourceCode;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	
               # Replace Windows newlines with Unix newlines	public String getSourceCodeDescription() {
               # Replace Windows newlines with Unix newlines		return this.sourceCodeDescription;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setSourceCodeDescription(String sourceCodeDescription) {
               # Replace Windows newlines with Unix newlines		this.sourceCodeDescription = sourceCodeDescription;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	
               # Replace Windows newlines with Unix newlines	public String getMappingType() {
               # Replace Windows newlines with Unix newlines		return this.mappingType;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setMappingType(String mappingType) {
               # Replace Windows newlines with Unix newlines		this.mappingType = mappingType;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines		public Integer getTargetConceptId() {
               # Replace Windows newlines with Unix newlines		return this.targetConceptId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setTargetConceptId(Integer targetConceptId) {
               # Replace Windows newlines with Unix newlines		this.targetConceptId = targetConceptId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	
               # Replace Windows newlines with Unix newlines	public Integer getTargetVocabularyId() {
               # Replace Windows newlines with Unix newlines		return this.targetVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setTargetVocabularyId(Integer targetVocabularyId) {
               # Replace Windows newlines with Unix newlines		this.targetVocabularyId = targetVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines		public Integer getSourceVocabularyId() {
               # Replace Windows newlines with Unix newlines		return this.sourceVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setSourceVocabularyId(Integer sourceVocabularyId) {
               # Replace Windows newlines with Unix newlines		this.sourceVocabularyId = sourceVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines}
               # Replace Windows newlines with Unix newlines