package edu.pitt.dbmi.ohdsiv5.db;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlinesimport java.util.List;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlinesimport org.hibernate.classic.Session;
               # Replace Windows newlines with Unix newlinesimport org.hibernate.criterion.Example;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlinesimport edu.pitt.dbmi.ohdsiv5.db.util.HibernateUtil;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines/**
               # Replace Windows newlines with Unix newlines * SourceToConceptMap generated by hbm2java
               # Replace Windows newlines with Unix newlines */
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public class SourceToConceptMap  {
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	// Fields    
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	/**
               # Replace Windows newlines with Unix newlines	 * 
               # Replace Windows newlines with Unix newlines	 */
               # Replace Windows newlines with Unix newlines	private static final long serialVersionUID = 1L;
               # Replace Windows newlines with Unix newlines	private Integer sourceToConceptMapId;
               # Replace Windows newlines with Unix newlines	private String sourceCode;
               # Replace Windows newlines with Unix newlines	private String sourceCodeDescription;
               # Replace Windows newlines with Unix newlines	private String mappingType;
               # Replace Windows newlines with Unix newlines	private Integer targetConceptId;
               # Replace Windows newlines with Unix newlines	private Integer targetVocabularyId;
               # Replace Windows newlines with Unix newlines	private Integer sourceVocabularyId;
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	// Constructors
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	/** default constructor */
               # Replace Windows newlines with Unix newlines	public SourceToConceptMap() {
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	/** minimal constructor */
               # Replace Windows newlines with Unix newlines	public SourceToConceptMap(String sourceCode, String mappingType, Integer targetConceptId, Integer targetVocabularyId, Integer sourceVocabularyId) {
               # Replace Windows newlines with Unix newlines		this.sourceCode = sourceCode;
               # Replace Windows newlines with Unix newlines		this.mappingType = mappingType;
               # Replace Windows newlines with Unix newlines		this.targetConceptId = targetConceptId;
               # Replace Windows newlines with Unix newlines		this.targetVocabularyId = targetVocabularyId;
               # Replace Windows newlines with Unix newlines		this.sourceVocabularyId = sourceVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	/** full constructor */
               # Replace Windows newlines with Unix newlines	public SourceToConceptMap(String sourceCode, String sourceCodeDescription, String mappingType, Integer targetConceptId, Integer targetVocabularyId, Integer sourceVocabularyId) {
               # Replace Windows newlines with Unix newlines		this.sourceCode = sourceCode;
               # Replace Windows newlines with Unix newlines		this.sourceCodeDescription = sourceCodeDescription;
               # Replace Windows newlines with Unix newlines		this.mappingType = mappingType;
               # Replace Windows newlines with Unix newlines		this.targetConceptId = targetConceptId;
               # Replace Windows newlines with Unix newlines		this.targetVocabularyId = targetVocabularyId;
               # Replace Windows newlines with Unix newlines		this.sourceVocabularyId = sourceVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	// Property accessors
               # Replace Windows newlines with Unix newlines			public String getSourceCode() {
               # Replace Windows newlines with Unix newlines		return this.sourceCode;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setSourceCode(String sourceCode) {
               # Replace Windows newlines with Unix newlines		this.sourceCode = sourceCode;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	
               # Replace Windows newlines with Unix newlines	public String getSourceCodeDescription() {
               # Replace Windows newlines with Unix newlines		return this.sourceCodeDescription;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setSourceCodeDescription(String sourceCodeDescription) {
               # Replace Windows newlines with Unix newlines		this.sourceCodeDescription = sourceCodeDescription;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	
               # Replace Windows newlines with Unix newlines	public String getMappingType() {
               # Replace Windows newlines with Unix newlines		return this.mappingType;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setMappingType(String mappingType) {
               # Replace Windows newlines with Unix newlines		this.mappingType = mappingType;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines		public Integer getTargetConceptId() {
               # Replace Windows newlines with Unix newlines		return this.targetConceptId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setTargetConceptId(Integer targetConceptId) {
               # Replace Windows newlines with Unix newlines		this.targetConceptId = targetConceptId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	
               # Replace Windows newlines with Unix newlines	public Integer getTargetVocabularyId() {
               # Replace Windows newlines with Unix newlines		return this.targetVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setTargetVocabularyId(Integer targetVocabularyId) {
               # Replace Windows newlines with Unix newlines		this.targetVocabularyId = targetVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines		public Integer getSourceVocabularyId() {
               # Replace Windows newlines with Unix newlines		return this.sourceVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	public void setSourceVocabularyId(Integer sourceVocabularyId) {
               # Replace Windows newlines with Unix newlines		this.sourceVocabularyId = sourceVocabularyId;
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines	/**
               # Replace Windows newlines with Unix newlines	 * Given a source concept id see if there is a common concept code for it
               # Replace Windows newlines with Unix newlines	 * return the id to the common code, otherwise return null
               # Replace Windows newlines with Unix newlines	 * 	 * 	 */
               # Replace Windows newlines with Unix newlines		public static Integer getConceptId(String sourceCode) {
               # Replace Windows newlines with Unix newlines		List<SourceToConceptMap>  results = null;
               # Replace Windows newlines with Unix newlines		Session session = HibernateUtil.getSession().getSessionFactory().getCurrentSession();
               # Replace Windows newlines with Unix newlines		if ( session != null ){
               # Replace Windows newlines with Unix newlines			SourceToConceptMap conceptMap = new SourceToConceptMap();
               # Replace Windows newlines with Unix newlines			conceptMap.setSourceCode(sourceCode);
               # Replace Windows newlines with Unix newlines			results = session.createCriteria(SourceToConceptMap.class)
               # Replace Windows newlines with Unix newlines			.add( Example.create(conceptMap) )
               # Replace Windows newlines with Unix newlines			.list();
               # Replace Windows newlines with Unix newlines		}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines		if (results == null || results.size() < 1){
               # Replace Windows newlines with Unix newlines			return 0;
               # Replace Windows newlines with Unix newlines		}
               # Replace Windows newlines with Unix newlines		else {
               # Replace Windows newlines with Unix newlines			return results.get(0).getTargetConceptId();
               # Replace Windows newlines with Unix newlines		}
               # Replace Windows newlines with Unix newlines	}
               # Replace Windows newlines with Unix newlines
               # Replace Windows newlines with Unix newlines}
               # Replace Windows newlines with Unix newlines