package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:47:01 PM by Hibernate Tools 3.1.0.beta4

import java.util.Calendar;


/**
 * VisitOccurrence generated by hbm2java
 */

public class VisitOccurrence  {

    // Fields    

    // Constructors

    /** default constructor */
    public VisitOccurrence() {
    }
    
    /** full constructor */
    public VisitOccurrence(Long visitOccurrenceId, Long personId, Calendar visitStartDate, Calendar visitEndDate, Integer visitConceptId) {
        this.visitOccurrenceId = visitOccurrenceId;
        this.personId = personId;
        this.visitStartDate = visitStartDate;
        this.visitEndDate = visitEndDate;
        this.visitConceptId = visitConceptId;
    }
       
    // Property accessors
                    Long visitOccurrenceId;
    public Long getVisitOccurrenceId() {
        return this.visitOccurrenceId;
    }    
    public void setVisitOccurrenceId(Long id) {
        this.visitOccurrenceId = id;
    }
    
        Long personId;
    public Long getPersonId() {
	return personId;
    }
    public void setPersonId(Long personId) {
	this.personId = personId;
    }  
   
        Calendar visitStartDate;
    public Calendar getVisitStartDate() {
        return this.visitStartDate;
    }    
    public void setVisitStartDate(Calendar visitStartDate) {
        this.visitStartDate = visitStartDate;
    }

        Calendar visitEndDate;
    public Calendar getVisitEndDate() {
        return this.visitEndDate;
    }
    public void setVisitDate(Calendar visitEndDate) {
        this.visitEndDate = visitEndDate;
    }
   
   
        Integer visitConceptId;
    public void setVisitConceptID(Integer condId) { 
	this.visitConceptId = condId;
    }
    public Integer getVisitConceptId() { 
	return visitConceptId;
    }






}
