package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:47:01 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * VisitOccurrence generated by hbm2java
 */
@Entity
@Table(name="VISIT_OCCURRENCE")

public class VisitOccurrence  implements java.io.Serializable {


    // Fields    

     private Long id;


    // Constructors

    /** default constructor */
    public VisitOccurrence() {
    }

    
    /** full constructor */
    public VisitOccurrence(Long id) {
        this.id = id;
    }
    

   
    // Property accessors
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="visitOccurrenceId", column=@Column(name="VISIT_OCCURRENCE_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=15, scale=0) ), 
        @AttributeOverride(name="visitStartDate", column=@Column(name="VISIT_START_DATE", unique=false, nullable=true, insertable=true, updatable=true, length=7) ), 
        @AttributeOverride(name="visitEndDate", column=@Column(name="VISIT_END_DATE", unique=false, nullable=true, insertable=true, updatable=true, length=7) ), 
        @AttributeOverride(name="personId", column=@Column(name="PERSON_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=12, scale=0) ), 
        @AttributeOverride(name="visitConceptId", column=@Column(name="VISIT_CONCEPT_ID", unique=false, nullable=true, insertable=true, updatable=true, precision=8, scale=0) ), 
        @AttributeOverride(name="sourceVisitCode", column=@Column(name="SOURCE_VISIT_CODE", unique=false, nullable=true, insertable=true, updatable=true, length=20) ) } )

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   








}
