package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:47:01 PM by Hibernate Tools 3.1.0.beta4

import java.util.Calendar;


/**
 * VisitOccurrence generated by hbm2java
 */
@Entity
@Table(name="VISIT_OCCURRENCE")

public class VisitOccurrence  {

    // Fields    

    // Constructors

    /** default constructor */
    public VisitOccurrence() {
    }
    
    /** full constructor */
    public VisitOccurrence(Long visitOccurrenceId, Long personId, Calendar visitStartDate, Calendar visitEndDate, Integer visitConceptId) {
        this.visitOccurrenceId = visitOccurrenceId;
        this.personId = personId;
        this.visitStartDate = visitStartDate;
        this.visitEndDate = visitEndDate;
        this.visitConceptId = visitConceptId;
    }
       
    // Property accessors
    @Id
    @Column(name="VISIT_OCCURRENCE_ID", unique=true, nullable=false, insertable=false, updatable=false, precision=15, scale=0)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="HIBERNATE_SEQUENCE_GENERATOR")
    @SequenceGenerator(name="HIBERNATE_SEQUENCE_GENERATOR", sequenceName="HIBERNATE_SEQUENCE", initialValue = 1, allocationSize = 1)
    Long visitOccurrenceId;
    public Long getVisitOccurrenceId() {
        return this.visitOccurrenceId;
    }    
    public void setVisitOccurrenceId(Long id) {
        this.visitOccurrenceId = id;
    }
    
    @Column(name="PERSON_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=12, scale=0) 
    Long personId;
    public Long getPersonId() {
	return personId;
    }
    public void setPersonId(Long personId) {
	this.personId = personId;
    }  
   
    @Column(name="VISIT_START_DATE", unique=false, nullable=true, insertable=true, updatable=true, length=7)
    Calendar visitStartDate;
    public Calendar getVisitStartDate() {
        return this.visitStartDate;
    }    
    public void setVisitStartDate(Calendar visitStartDate) {
        this.visitStartDate = visitStartDate;
    }

    @Column(name="VISIT_END_DATE", unique=false, nullable=true, insertable=true, updatable=true, length=7)
    Calendar visitEndDate;
    public Calendar getVisitEndDate() {
        return this.visitEndDate;
    }
    public void setVisitDate(Calendar visitEndDate) {
        this.visitEndDate = visitEndDate;
    }
   
   
    @Column(name="VISIT_CONCEPT_ID", unique=false, nullable=true, insertable=true, updatable=true, precision=8, scale=0)
    Integer visitConceptId;
    public void setVisitConceptID(Integer condId) { 
	this.visitConceptId = condId;
    }
    public Integer getVisitConceptId() { 
	return visitConceptId;
    }






}
